version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/opt/bitnami/php/etc/conf.d/xdebug.ini
      - ./docker/custom_php.ini:/opt/bitnami/php/etc/conf.d/custom_php.ini
      - ./docker/mhsendmail:/usr/local/bin/mhsendmail
    # privileged: true # Privileged mode could be required to run this container under Windows
  mailhog:
    image: mailhog/mailhog
    ports:
    - "3025:8025"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}